name: Build and upload executable on Release

on:
  release:
    types: [published]

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name=TakeAttendance src/main.py

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TakeAttendance.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
